# Generated by Django 4.1.7 on 2023-04-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationcomment',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
