# Generated by Django 4.1.7 on 2023-04-05 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_publicationcomment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationcomment',
            name='dateComment',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
