# Generated by Django 4.1.7 on 2023-04-05 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='dateRequest',
            new_name='dateAccept',
        ),
    ]
