# Generated by Django 4.1.7 on 2023-04-02 07:41

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepicture',
            name='isCurrent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='image_url',
            field=models.ImageField(upload_to=user.models.upload_pdp),
        ),
    ]
