# Generated by Django 4.1.7 on 2023-04-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profilepicture_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeuser',
            name='dateJoin',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
